### PR TITLE
Mention Safe Browsing benefit in customtabs.html

### PR DESCRIPTION
**Pull request by ngparker**
WebView does not currently support Safe Browsing checks.

### CODE REVIEW

**Comment by ngparker** [comment]
I signed the CLA, and I am nparker@google.com.

**Comment by paulirish** [comment]
lgtm.. cc @PaulKinlan for the review

**Comment by addyosmani** [comment]
LGTM2

**Comment by PaulKinlan** [comment]
Thanks.  sorry for delay.

**Pull request merged**
